name: qc-build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Checkout Submodule
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.ACTIONS_TOKEN }}
          submodules: recursive

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build with Gradle Wrapper
        run: ./gradlew :qc-api-container:build -x test

      - name: docker image build
        run: docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/questioncloud .

      - name: docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: docker Hub push
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/questioncloud

      - name: deploy
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.REMOTE_IP }} # 인스턴스 IP
          username: ${{ secrets.REMOTE_USER }} # 우분투 아이디
          key: ${{ secrets.REMOTE_PRIVATE_KEY }} # ec2 instance pem key
          port: ${{ secrets.REMOTE_SSH_PORT }} # 접속포트
          script: |
            cd ~
            sudo ./deploy.sh
